# Generated by Django 5.2.5 on 2025-09-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст коментаря')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BinLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Create_Bins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='Посилання на файл')),
                ('file_key', models.CharField(blank=True, help_text='Шлях до файлу у бакеті (наприклад, bins/bin_123.txt)', max_length=255, null=True, verbose_name='Ключ файлу R2')),
                ('content', models.TextField(help_text='Введіть текст для збереження у bin', verbose_name='Вміст')),
                ('category', models.CharField(blank=True, choices=[('NONE', 'Без категорії'), ('Cryptocurrency', 'Криптовалюта'), ('Cybersecurity', 'Кібербезпека'), ('Fixit', 'Виправлення'), ('Food', 'Їжа'), ('Gaming', 'Ігри'), ('Haiku', 'Хайку'), ('Help', 'Допомога'), ('History', 'Історія'), ('Housing', 'Житло'), ('Jokes', 'Жарти'), ('legal', 'Юридичні питання'), ('Money', 'Гроші'), ('Movies', 'Фільми'), ('Music', 'Музика'), ('Pets', 'Домашні тварини'), ('Photos', 'Фотографії'), ('Science', 'Наука'), ('Software', 'Програмне забезпечення'), ('Source Code', 'Вихідний код'), ('Spirit', 'Дух'), ('Sport', 'Спорт'), ('Travel', 'Подорожі'), ('TW', 'Телебачення'), ('Writing', 'Письмо')], default='NONE', help_text='Виберіть категорію для bin', max_length=50, verbose_name='Категорія')),
                ('tags', models.CharField(blank=True, help_text='Введіть теги через кому для кращої організації', max_length=200, verbose_name='Теги')),
                ('language', models.CharField(blank=True, choices=[('none', 'Без мови'), ('c', 'C'), ('c#', 'C#'), ('cpp', 'C++'), ('css', 'CSS'), ('html', 'HTML'), ('java', 'Java'), ('javascript', 'JavaScript'), ('lua', 'Lua'), ('objective-c', 'Objective-C'), ('php', 'PHP'), ('perl', 'Perl'), ('python', 'Python'), ('ruby', 'Ruby'), ('swift', 'Swift')], default='none', help_text='Виберіть мову для підсвітки синтаксису', max_length=50, verbose_name='Мова')),
                ('expiry', models.CharField(choices=[('never', 'Ніколи'), ('1m', '1 хвилина'), ('1h', '1 година'), ('12h', '12 годин'), ('1d', '1 день'), ('7d', '7 днів'), ('2w', '2 тижні'), ('30d', '30 днів'), ('6mo', '6 місяців'), ('1y', '1 рік')], default='never', help_text='Виберіть, коли цей bin має бути видалений', max_length=50, verbose_name='Термін дії')),
                ('expiry_at', models.DateTimeField(blank=True, null=True, verbose_name='Bin видаляється після')),
                ('access', models.CharField(choices=[('public', 'Публічний'), ('private', 'Приватний')], default='public', help_text='Виберіть, яким буде цей bin, публічним або приватним', max_length=50, verbose_name='Доступність')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Назва')),
                ('size_bin', models.PositiveIntegerField(default=0, help_text='Розмір вмісту в байтах', verbose_name='Розмір (байт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Кількість лайків')),
                ('dislikes_count', models.PositiveIntegerField(default=0, verbose_name='Кількість дизлайків')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів')),
                ('hash', models.CharField(blank=True, help_text='SHA-256 хеш вмісту для унікальності', max_length=64, null=True, unique=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'Bin',
                'verbose_name_plural': 'Bins',
                'db_table': 'create_bin',
            },
        ),
        migrations.CreateModel(
            name='ViewBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('session_key', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
