# Generated by Django 5.2.4 on 2025-09-02 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Bins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Введіть текст для збереження у bin', verbose_name='Вміст')),
                ('category', models.CharField(choices=[('NONE', 'Без категорії'), ('Cryptocurrency', 'Криптовалюта'), ('Cybersecurity', 'Кібербезпека'), ('Fixit', 'Виправлення'), ('Food', 'Їжа'), ('Gaming', 'Ігри'), ('Haiku', 'Хайку'), ('Help', 'Допомога'), ('History', 'Історія'), ('Housing', 'Житло'), ('Jokes', 'Жарти'), ('legal', 'Юридичні питання'), ('Money', 'Гроші'), ('Movies', 'Фільми'), ('Music', 'Музика'), ('Pets', 'Домашні тварини'), ('Photos', 'Фотографії'), ('Science', 'Наука'), ('Software', 'Програмне забезпечення'), ('Source Code', 'Вихідний код'), ('Spirit', 'Дух'), ('Sport', 'Спорт'), ('Travel', 'Подорожі'), ('TW', 'Телебачення'), ('Writing', 'Письмо')], default='NONE', help_text='Виберіть категорію для bin', max_length=50, verbose_name='Категорія')),
                ('tags', models.CharField(blank=True, help_text='Введіть теги через кому для кращої організації', max_length=200, verbose_name='Теги')),
                ('language', models.CharField(choices=[('none', 'Без мови'), ('c', 'C'), ('c#', 'C#'), ('cpp', 'C++'), ('css', 'CSS'), ('html', 'HTML'), ('java', 'Java'), ('javascript', 'JavaScript'), ('lua', 'Lua'), ('objective-c', 'Objective-C'), ('php', 'PHP'), ('perl', 'Perl'), ('python', 'Python'), ('ruby', 'Ruby'), ('swift', 'Swift')], default='none', help_text='Виберіть мову для підсвітки синтаксису', max_length=50, verbose_name='Мова')),
                ('expiry', models.CharField(choices=[('never', 'Ніколи'), ('1m', '1 хвилина'), ('1h', '1 година'), ('12h', '12 годин'), ('1d', '1 день'), ('7d', '7 днів'), ('2w', '2 тижні'), ('30d', '30 днів'), ('6mo', '6 місяців'), ('1y', '1 рік')], default='never', help_text='Виберіть, коли цей bin має бути видалений', max_length=50, verbose_name='Термін дії')),
                ('access', models.CharField(choices=[('public', 'Публічний'), ('private', 'Приватний')], default='public', help_text='Виберіть, яким буде цей bin, публічним або приватним', max_length=50, verbose_name='Доступність')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'db_table': 'create_bin',
            },
        ),
    ]
