# Generated by Django 5.2.4 on 2025-09-17 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_viewbin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='create_bins',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість дизлайків'),
        ),
        migrations.AddField(
            model_name='create_bins',
            name='file_key',
            field=models.CharField(blank=True, help_text='Шлях до файлу у бакеті (наприклад, bins/bin_123.txt)', max_length=255, null=True, verbose_name='Ключ файлу R2'),
        ),
        migrations.AddField(
            model_name='create_bins',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість лайків'),
        ),
        migrations.AddField(
            model_name='create_bins',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів'),
        ),
        migrations.CreateModel(
            name='BinLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='bins.create_bins')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
