# Generated by Django 5.2 on 2025-12-18 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_bins',
            name='expiry',
            field=models.CharField(choices=[('never', 'Ніколи'), ('1m', '1 хвилина'), ('1h', '1 година'), ('12h', '12 годин'), ('1d', '1 день'), ('1w', '1 тиждень'), ('2w', '2 тижні'), ('30d', '30 днів'), ('6mo', '6 місяців'), ('1y', '1 рік')], default='never', help_text='Виберіть, коли цей bin має бути видалений', max_length=50, verbose_name='Термін дії'),
        ),
        migrations.AlterField(
            model_name='create_bins',
            name='language',
            field=models.CharField(blank=True, choices=[('none', 'Без мови'), ('bash', 'Bash'), ('c++', 'C++'), ('java', 'Java'), ('javascript', 'JavaScript'), ('python', 'Python'), ('ruby', 'Ruby'), ('swift', 'Swift')], default='none', help_text='Виберіть мову для підсвітки синтаксису', max_length=50, verbose_name='Мова'),
        ),
        migrations.AlterUniqueTogether(
            name='binlike',
            unique_together={('bin', 'user')},
        ),
    ]
