# Generated by Django 5.2.5 on 2025-09-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0004_bincomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_bins',
            name='size_bin',
            field=models.PositiveIntegerField(default=0, help_text='Розмір вмісту в байтах', verbose_name='Розмір (байт)'),
        ),
    ]
